[package]
name = "braindump"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
llm-chain = "0.11.2"
llm-chain-openai = "0.11.1"
tokio = { version = "1.28.1", features = ["full"] }
