[package]
name = "braindump"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
llm-chain = "0.12.3"
llm-chain-openai = "0.13.0"
tokio = { version = "1.42.0", features = ["full"] }
